config/routes.rb
Izotorg::Application.routes.draw do

  devise_for :admins

  devise_for :users

  get "admin", to: "admin/home#index"
  namespace :admin do
    resources :users
    resources :manufacturers
    resources :products
  end

  resources :users

  mount Ckeditor::Engine => '/ckeditor'  

  resources :manufacturers, only: [ :index, :show ] do
    resources :products, only: [ :index, :show ]
  end

  resource :static_pages, only: [] do
    ["index", "about", "products", "articles", "partners", "price", "contacts"].each do |static_page|
      get static_page
    end
  end

  root to: 'users#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/ckeditor/application.rb
config.autoload_paths += %W(#{config.root}/app/models/ckeditor)

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  attr_accessible :content, :logo, :title, :remote_logo_url

  has_many :products, dependent: :destroy

  mount_uploader :logo, LogoUploader

   def full_title
  	title
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :content, :image, :manufacturer_id, :title, :remote_image_url

  belongs_to :manufacturer

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
 # attr_accessible :email, :name
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController

	layout "admin"
	
  def index
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  layout "admin"
  
  def index
    @users = User.order("created_at").page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      flash[:success] = "User was successfully updated!"
      redirect_to admin_user_path(@user) 
    else
      render action: "edit" 
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to admin_users_url 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  def index
    @manufacturers = Manufacturer.order("created_at").page(params[:page]).per(5) 
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :find_the_manufacturer


  def index
    @products = @manufacturer.products.order("created_at").page(params[:page]).per(5)
  end

  def show
    @product = @manufacturer.products.find(params[:id])
  end


  private

  def find_the_manufacturer
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  layout "new_design"

  def index
  end

  def about
  end

  def products
  end

  def articles
  end

  def partners
  end

  def price
  end

  def contacts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @users = User.order("created_at").page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url 
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/manufacturers_helper.rb
module Admin::ManufacturersHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Создать", class: "btn btn-mini btn-inverse" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<%= render 'form' %>

<%= link_to 'Обзор', admin_user_path(@user), class: "btn btn-mini btn-info" %> |
<%= link_to 'Возврат', admin_users_path, class: "btn btn-mini btn-success" %>

app/views/admin/users/index.html.erb
<h1 style="margin-top: 30px;">Пользователи</h1>

<%= paginate @users %>

<table class="table table-bordered">
  <tr>
    <th>Имя</th>
    <th>Email</th>
    <th>Кнопки управления</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td>
      <%= link_to 'Обзор', admin_user_path(user), class: "btn btn-mini btn-info" %>
      <%= link_to 'Изменение', edit_admin_user_path(user), class: "btn btn-mini btn-warning" %>
      <%= link_to 'Удаление', admin_user_path(user), class: "btn btn-mini btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/admin/users/new.html.erb
<h1>Новый пользователь</h1>

<%= render 'form' %>

<%= link_to 'Возврат', admin_users_path, class: "btn btn-mini btn-success" %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Имя:</b><br />
  <%= @user.name %>
</p>

<p>
  <b>Email:</b><br />
  <%= @user.email %>
</p>


<%= link_to 'Изменение', edit_admin_user_path(@user), class: "btn btn-mini btn-warning" %> |
<%= link_to 'Возврат', admin_users_path, class: "btn btn-mini btn-success" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<%= render 'form' %>

<%= link_to 'Обзор', @user %> |
<%= link_to 'Возврат', users_path %>

app/views/users/index.html.erb
<h1>Пользователи</h1>

<%= paginate @users %>

<table>
  <tr>
    <th>Имя</th>
    <th>Email</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Обзор', user %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Новый пользователь</h1>

<%= render 'form' %>

<%= link_to 'Возврат', users_path %>

app/views/users/show.html.erb
 <p id="notice"><%= notice %></p>

<p>
  <b>Имя:</b><br />
  <%= @user.name %>
</p>

<p>
  <b>Email:</b><br />
  <%= @user.email %>
</p>


<%= link_to 'Возврат', users_path %>