config/routes.rb
Izotorg::Application.routes.draw do

  devise_for :admins

  devise_for :users

  get "admin", to: "admin/home#index"
  namespace :admin do
    resources :users
    resources :manufacturers
    resources :products
  end

  resources :users

  mount Ckeditor::Engine => '/ckeditor'  

  resources :manufacturers, only: [ :index, :show ] do
    resources :products, only: [ :index, :show ]
  end

  resource :static_pages, only: [] do
    ["index", "about", "products", "articles", "partners", "price", "contacts"].each do |static_page|
      get static_page
    end
  end

  root to: 'users#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/ckeditor/application.rb
config.autoload_paths += %W(#{config.root}/app/models/ckeditor)

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  attr_accessible :content, :logo, :title, :remote_logo_url

  has_many :products, dependent: :destroy

  mount_uploader :logo, LogoUploader

   def full_title
  	title
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :content, :image, :manufacturer_id, :title, :remote_image_url

  belongs_to :manufacturer

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
 # attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  def index
    @manufacturers = Manufacturer.order("created_at").page(params[:page]).per(5) 
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :find_the_manufacturer


  def index
    @products = @manufacturer.products.order("created_at").page(params[:page]).per(5)
  end

  def show
    @product = @manufacturer.products.find(params[:id])
  end


  private

  def find_the_manufacturer
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  layout "new_design"

  def index
  end

  def about
  end

  def products
  end

  def articles
  end

  def partners
  end

  def price
  end

  def contacts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @users = User.order("created_at").page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url 
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_favicon.html.erb
<!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; Company 2013</p>
</footer>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Панель", admin_path %></li>
          <li><%= link_to "Производитель", admin_manufacturers_path %></li>
          <li><%= link_to "Продукция",   admin_products_path %></li>
          <li><%= link_to "Пользователи", admin_users_path %></li>
        </ul>
        
        <ul class="nav pull-right">
          <li><%= link_to "Выход", destroy_admin_session_path, method: :delete %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
	<ul class="nav nav-list">
	  <li class="nav-header">Управление</li>
	  <li><%= link_to "Производитель", admin_manufacturers_path %></li>
	  <li><%= link_to "Продукция",  admin_products_path %></li>
	  <li><%= link_to "Пользователи", admin_users_path %></li>
	</ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/_user_nav.html.erb
<div id="user_nav">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Registration', new_user_registration_path %>
    <%= link_to 'Login', new_user_session_path %>
  <% end %>			
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Izotorg" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin/application", :media => "all" %>
    <%= render 'layouts/favicon' %> 
    <%= javascript_include_tag "admin/application" %>
  </head>
  <body>
    <%= render 'layouts/navigation' %> 
    <div class="container main_con">
      <div class="row">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <%= render 'layouts/sidebar' %>
      </div><!--/row-->
      <%= render 'layouts/footer' %>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Izotorg</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="user_nav">
	  <% if user_signed_in? %>
	    Logged in as <strong><%= current_user.email %></strong>.
	    <%= link_to 'Edit profile', edit_user_registration_path %>
	    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
	  <% else %>
	    <%= link_to 'Registration', new_user_registration_path %>
	    <%= link_to 'Login', new_user_session_path %>
	  <% end %>			
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/new_design.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Izotorg</title>
    <%= stylesheet_link_tag    "new_design", :media => "all" %>
    <%= javascript_include_tag "new_design" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>